name: Build and Upload Artifact (C++)

on:
  push:
    branches:
      - main
      - jobs/*

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MinGW for Windows
        run: |
          choco install mingw
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH
          echo "C:\Program Files\mingw-w64\mingw64\bin" >> $GITHUB_PATH

      - name: Verify Compiler
        run: g++ --version

      - name: Cache Google Test
        uses: actions/cache@v3
        with:
          path: googletest/build
          key: ${{ runner.os }}-googletest

      - name: Prepare Google Test
        run: |
          if (!(Test-Path "googletest")) { git clone https://github.com/google/googletest.git }
          if (!(Test-Path "googletest/build")) { New-Item -ItemType Directory -Path "googletest/build" }
        shell: pwsh

      - name: Build Google Test
        run: |
          cd googletest/build
          if (!(Test-Path "lib/libgtest.a")) { cmake -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER=g++ ..; mingw32-make }
        shell: pwsh
  

      - name: Build project (Windows) with static linking
        run: make

      - name: Build and Run Tests (Windows)
        run: make test

      - name: Debug Build Directory (Windows)
        run: dir build

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app-windows
          path: build/app.exe
