name: Build and Test (Windows)

on:
  push:
    branches:
      - main
      - jobs/*

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install MinGW
        run: |
          choco install mingw
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH
          echo "C:\Program Files\mingw-w64\mingw64\bin" >> $GITHUB_PATH

      - name: Verify compiler
        run: g++ --version

      - name: Build Google Test
        run: make $(GTEST_BUILD)/lib/libgtest.a

      - name: Build project (Windows)
        run: make

      - name: Build and Run Tests (Windows)
        run: make test

      - name: Upload compiled application as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app-windows
          path: build/app.exe
