name: Build and Test (Cross-Platform)

on:
  push:
    branches:
      - main
      - jobs/*
      - tests/*

jobs:
  build-ubuntu:
    name: Build and Test on Ubuntu (Valgrind)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind g++ make

      - name: Build Google Test
        run: make external/googletest/build/lib/libgtest.a

      - name: Build project
        run: make all

      - name: Run tests with Valgrind
        run: |
          valgrind --error-exitcode=1 --leak-check=full ./build/app.exe

  build-windows:
    name: Build and Test on Windows
    runs-on: windows-latest
    needs: build-ubuntu
    if: success()

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install MinGW
        run: |
          choco install mingw
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH
          echo "C:\Program Files\mingw-w64\mingw64\bin" >> $GITHUB_PATH

      - name: Verify compiler
        run: g++ --version

      - name: Build Google Test
        run: make external/googletest/build/lib/libgtest.a

      - name: Build project (Windows)
        run: make all

      - name: Build and Run Tests (Windows)
        run: make test

      - name: Upload compiled application as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app-windows
          path: build/app.exe
