name: Build and Test (Windows)

on:
  push:
    branches:
      - main
      - jobs/*

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MinGW for Windows
        run: |
          choco install mingw
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH
          echo "C:\Program Files\mingw-w64\mingw64\bin" >> $GITHUB_PATH

      - name: Verify Compiler
        run: g++ --version

      - name: Cache Google Test
        uses: actions/cache@v3
        with:
          path: googletest/install
          key: windows-googletest

      - name: Build Google Test
        shell: pwsh
        run: |
          if (!(Test-Path "googletest")) { git clone https://github.com/google/googletest.git }
          if (!(Test-Path "googletest/build")) { New-Item -ItemType Directory -Path "googletest/build" }
          cd googletest/build
          cmake -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=../install ..
          mingw32-make
          mingw32-make install

      - name: Set environment variables for Google Test
        run: |
          echo "GTEST_HOME=$GITHUB_WORKSPACE/googletest/install" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/googletest/install/lib" >> $GITHUB_PATH

      - name: Build project (Windows) with static linking
        run: make all

      - name: Build and Run Tests (Windows)
        run: make test

      - name: Run Google Test Executable
        run: $GITHUB_WORKSPACE/build/test_runner.exe

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app-windows
          path: build/app.exe
